# Generated by Django 4.0 on 2022-02-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15, verbose_name='Дата занятия')),
                ('groups', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='journal.group', verbose_name='Группа на занятии')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_Students', models.DateField(verbose_name='Студент вступил в группу')),
                ('output_Students', models.DateField(blank=True, verbose_name='Студент покинул группу')),
                ('groups', models.ManyToManyField(to='journal.Group', verbose_name='Группа')),
                ('students', models.ManyToManyField(to='journal.Student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(default='Да', max_length=3, verbose_name='Присутсвие')),
                ('grade', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка за занятие')),
                ('lessons', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='journal.lesson', verbose_name='Занятия')),
                ('students', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='journal.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Успеваемость',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subjects',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='journal.subject', verbose_name='Проведенные занятия'),
        ),
    ]
