# Generated by Django 4.0 on 2022-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentingroup',
            name='output_Students',
            field=models.DateField(blank=True, null=True, verbose_name='Студент покинул группу'),
        ),
    ]
