# Generated by Django 4.0 on 2022-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_studentingroup_output_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentingroup',
            name='groups',
            field=models.ManyToManyField(related_name='StudentInGroup', to='journal.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentingroup',
            name='students',
            field=models.ManyToManyField(related_name='Group', to='journal.Student', verbose_name='Студент'),
        ),
    ]
