# Generated by Django 4.0 on 2022-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_studentingroup_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дата занятия'),
        ),
    ]
