# Generated by Django 4.0 on 2022-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Дата занятия'),
        ),
    ]
