# Generated by Django 4.0 on 2022-04-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='lessons',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.lesson', verbose_name='Занятия'),
        ),
    ]
